services:
  client:
    image: ghcr.io/up9t/game-tic-tac-toe/frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
  
  server:
    image: ghcr.io/up9t/game-tic-tac-toe/backend:latest
    build:
      context: ./server
      dockerfile: Dockerfile
